### ISSUE TITLE
ModuleNotFoundError: No module named 'uvloop'

### ISSUE THREAD

**Issue by timboft** [kanewi11/telegram-reposter#1]
что делать если запускаю на виндовс и не находит этот модуль?

**Comment by kanewi11** [comment]
Щас решу проблему, подожди

**Comment by timboft** [comment]
ок жду

**Comment by kanewi11** [comment]
> ок жду

сделай pull или скачай архив заново, пофиксил

**Comment by timboft** [comment]
хорошо,щас скачаю

**Comment by kanewi11** [comment]
> хорошо,щас скачаю

Если что обращайся

**Comment by timboft** [comment]
хорошо
