### ISSUE TITLE
проблема с кодировкой

### ISSUE THREAD

**Issue by timboft** [kanewi11/telegram-reposter#2]
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 51: character maps to <undefined>
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 155, in main
    ret = method(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 548, in runcode
    exec(code, self.locals)
  File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter.py", line 25, in <module>
    vk_poster = VkPoster(VK_ACCESS_TOKEN, VK_GROUP_ID, REPOST_VK)
  File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter\send\vk\vk.py", line 53, in __init__
    logger.info('VK постер включен ✅')
Message: 'VK постер включен ✅'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 59: character maps to <undefined>
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 155, in main
    ret = method(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 548, in runcode
    exec(code, self.locals)
  File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter.py", line 26, in <module>
    inst_poster = InstPoster(INST_LOGIN, INST_PASSWORD, PROXY, REPOST_INST)
  File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter\send\instagram\instagram.py", line 45, in __init__
    logger.info('Instagram постер выключен ❌')
Message: 'Instagram постер выключен ❌'
Arguments: ()

**Comment by kanewi11** [comment]
Ок, ща фиксану, забыл про кодировку на винде

**Comment by kanewi11** [comment]
Готово, я просто на винде вообще не тестил, сори 

> TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
> --- Logging error ---
> Traceback (most recent call last):
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\logging__init__.py", line 1084, in emit
> stream.write(msg + self.terminator)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
> return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 51: character maps to 
> Call stack:
> File "", line 1, in 
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 155, in main
> ret = method(*args, **kwargs)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 548, in runcode
> exec(code, self.locals)
> File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter.py", line 25, in 
> vk_poster = VkPoster(VK_ACCESS_TOKEN, VK_GROUP_ID, REPOST_VK)
> File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter\send\vk\vk.py", line 53, in **init**
> logger.info('VK постер включен ✅')
> Message: 'VK постер включен ✅'
> Arguments: ()
> --- Logging error ---
> Traceback (most recent call last):
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\logging__init__.py", line 1084, in emit
> stream.write(msg + self.terminator)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 19, in encode
> return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 59: character maps to 
> Call stack:
> File "", line 1, in 
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 155, in main
> ret = method(*args, **kwargs)
> File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\idlelib\run.py", line 548, in runcode
> exec(code, self.locals)
> File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter.py", line 26, in 
> inst_poster = InstPoster(INST_LOGIN, INST_PASSWORD, PROXY, REPOST_INST)
> File "C:\Users\Admin\Desktop\telegram-reposter-main\telegram-reposter-main\reposter\send\instagram\instagram.py", line 45, in **init**
> logger.info('Instagram постер выключен ❌')
> Message: 'Instagram постер выключен ❌'
> Arguments: ()

**Comment by kanewi11** [comment]
Завелось? У меня просто нет щас возможности на win протестить)

**Comment by timboft** [comment]
короче с телеги парсит все как положено в папку files,но на стену в вк не хочет публиковать,ни в какую,токен рабочий,id паблика тоже правильный,все что нужно установил,пробовал на 3 машинах,результат не публикует на стену

**Comment by kanewi11** [comment]
Странно, у меня публиковал вообще все, от файлов, до картинок и текста

**Comment by kanewi11** [comment]
Лог чистый?

**Comment by timboft** [comment]
2fa в вк никак же не влияет?авторизация же по токену идет,время на винде проверь!

**Comment by timboft** [comment]
время будет на винде проверь

**Comment by kanewi11** [comment]
> время будет на винде проверь

Окей, там просто бот запущен 24/7, трогать не могу, как тест его пройдет протестирую. Ща на маке тестану

**Comment by timboft** [comment]
публикация же сразу должна идти в вк при появление новых постов в телеге?задержки же нет никакой?

**Comment by kanewi11** [comment]
+- 10 сек на проверку базы и + время на загрузку файлов на сервер вк

**Comment by timboft** [comment]
версия питона играет какую нить роль?

**Comment by kanewi11** [comment]
Тестил только на 3.10, думаю на версиях ниже 3.8 могут быть баги, но если бы были проблемы, то была бы ошибка

**Comment by timboft** [comment]
ну я как раз и тестил на 3.8 ,может и в правду нормально не запускается на версиях ниже,щас буду тестить

**Comment by kanewi11** [comment]
Я вообще токен не могу получить вк

**Comment by timboft** [comment]
ну я по инструкции все делал,получил с первого раза,ну и пробовал еще через https://vkhost.github.io/ там в настройках настроишь

**Comment by kanewi11** [comment]
> ну я по инструкции все делал,получил с первого раза,ну и пробовал еще через https://vkhost.github.io/ там в настройках настроишь

У меня все робит

**Comment by timboft** [comment]
ну щас 3.10 версию поставлю и проверю

**Comment by kanewi11** [comment]
А у в логах ошибок нет? `telegram-reposter/reposter/logs/app.log`

**Comment by timboft** [comment]
нет,там четко написано что все работает

**Comment by kanewi11** [comment]
> нет,там четко написано что все работает

Ну тогда как комп освободиться посмотрю че там не работает. Хотя если не отправилось, то должна быть ошибка

**Comment by kanewi11** [comment]
> нет,там четко написано что все работает

Могу только предложить тебе запустить на линуксе, если и там не работает, то тут уже проблема не в коде, мб в токене права не все.

**Comment by timboft** [comment]
после тестов с версией 3.10 отпишу,скажу работает или нет,возможно дедик хреновый попался

**Comment by kanewi11** [comment]
> после тестов с версией 3.10 отпишу,скажу работает или нет,возможно дедик хреновый попался
> 
> 

Прям 3.10 не ставь, там с некоторыми библиотеками баги есть. Ставь 3.10.*

**Comment by timboft** [comment]
понял

**Comment by timboft** [comment]
а у тебя какая версия питона?

**Comment by kanewi11** [comment]
> а у тебя какая версия питона?

3.10.9

**Comment by timboft** [comment]
да вот хуйня замучала ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by kanewi11** [comment]
> да вот хуйня замучала ModuleNotFoundError: No module named 'sqlalchemy'

pip install -r requirements_win.txt

**Comment by timboft** [comment]
да тоже самое,я уже раз 10 пробовал

**Comment by kanewi11** [comment]
> да тоже самое,я уже раз 10 пробовал

Значит ты где-то накосячил)

**Comment by timboft** [comment]
буду разбиратся щас
