### ISSUE TITLE
Ошибки не выдает, но и не работает. 

### ISSUE THREAD

**Issue by IncredibleRob** [kanewi11/telegram-reposter#3]
Ошибки не выдает, но и не работает. А суть репостера мне нравится!

**Comment by kanewi11** [comment]
> Ошибки не выдает, но и не работает. А суть репостера мне нравится!


Какая ос Win, mac, linux?

**Comment by kanewi11** [comment]
Я чуть-чуть погодя перепроверю, но мне другой человек писал, у него не работало на win, у меня на mac все шикарно было. В общем перепроверю и напишу сюда.

**Comment by IncredibleRob** [comment]
> > Ошибки не выдает, но и не работает. А суть репостера мне нравится!
> 
> Какая ос Win, mac, linux?

Win 11, Python 3.11

**Comment by IncredibleRob** [comment]
> Я чуть-чуть погодя перепроверю, но мне другой человек писал, у него не работало на win, у меня на mac все шикарно было. В общем перепроверю и напишу сюда.

Уважаемый автор, как дела? ^_^

**Comment by kanewi11** [comment]
Помню, но щас очень сильно занят еще пару дней минимум. Я отвечу как потестирую. Попробуй на линуксе, если есть такая возможность.

**Comment by kanewi11** [comment]
> > Я чуть-чуть погодя перепроверю, но мне другой человек писал, у него не работало на win, у меня на mac все шикарно было. В общем перепроверю и напишу сюда.
> 
> Уважаемый автор, как дела? ^_^

Все работает на win, проверь id группы вк, там должны быть только цифры например:

https://vk.com/club220688189

id будет 220688189

Но там есть один баг с русским языком, я его поправил но залью обнову попозже
